sudo: false

language: cpp

install:
    - wget --no-check-certificate -qO- https://cmake.org/files/v3.1/cmake-3.5.2-Linux-x86_64.tar.gz | tar xvz

compiler:
    - gcc

before_script:
    - export CC=gcc-5
    - export CXX=g++-5

script:
    - mkdir -p build
    - cd build
    - ../cmake-3.5.2-Linux-x86_64/bin/cmake -DCMAKE_BUILD_TYPE=Release ..
    - make

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-5
            - g++-5
