sudo: required
dist: trusty
language: cpp

install:
    - wget -qO- https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz | tar xvz

compiler:
    - clang
    - gcc

script:
    - mkdir -p build
    - cd build
    - ../cmake-3.5.2-Linux-x86_64/bin/cmake -DCMAKE_BUILD_TYPE=Release ..
    - make
